/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaskRouteImport } from './routes/task'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsTrWithoutOtelTransferRouteImport } from './routes/docs/tr/without-otel-transfer'
import { Route as DocsTrWithoutOtelRouteImport } from './routes/docs/tr/without-otel'
import { Route as DocsTrWithOtelRouteImport } from './routes/docs/tr/with-otel'
import { Route as DocsEnWithoutOtelTransferRouteImport } from './routes/docs/en/without-otel-transfer'
import { Route as DocsEnWithoutOtelRouteImport } from './routes/docs/en/without-otel'
import { Route as DocsEnWithOtelRouteImport } from './routes/docs/en/with-otel'

const TaskRoute = TaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTrWithoutOtelTransferRoute =
  DocsTrWithoutOtelTransferRouteImport.update({
    id: '/tr/without-otel-transfer',
    path: '/tr/without-otel-transfer',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsTrWithoutOtelRoute = DocsTrWithoutOtelRouteImport.update({
  id: '/tr/without-otel',
  path: '/tr/without-otel',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsTrWithOtelRoute = DocsTrWithOtelRouteImport.update({
  id: '/tr/with-otel',
  path: '/tr/with-otel',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsEnWithoutOtelTransferRoute =
  DocsEnWithoutOtelTransferRouteImport.update({
    id: '/en/without-otel-transfer',
    path: '/en/without-otel-transfer',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsEnWithoutOtelRoute = DocsEnWithoutOtelRouteImport.update({
  id: '/en/without-otel',
  path: '/en/without-otel',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsEnWithOtelRoute = DocsEnWithOtelRouteImport.update({
  id: '/en/with-otel',
  path: '/en/with-otel',
  getParentRoute: () => DocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/task': typeof TaskRoute
  '/docs/en/with-otel': typeof DocsEnWithOtelRoute
  '/docs/en/without-otel': typeof DocsEnWithoutOtelRoute
  '/docs/en/without-otel-transfer': typeof DocsEnWithoutOtelTransferRoute
  '/docs/tr/with-otel': typeof DocsTrWithOtelRoute
  '/docs/tr/without-otel': typeof DocsTrWithoutOtelRoute
  '/docs/tr/without-otel-transfer': typeof DocsTrWithoutOtelTransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/task': typeof TaskRoute
  '/docs/en/with-otel': typeof DocsEnWithOtelRoute
  '/docs/en/without-otel': typeof DocsEnWithoutOtelRoute
  '/docs/en/without-otel-transfer': typeof DocsEnWithoutOtelTransferRoute
  '/docs/tr/with-otel': typeof DocsTrWithOtelRoute
  '/docs/tr/without-otel': typeof DocsTrWithoutOtelRoute
  '/docs/tr/without-otel-transfer': typeof DocsTrWithoutOtelTransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/task': typeof TaskRoute
  '/docs/en/with-otel': typeof DocsEnWithOtelRoute
  '/docs/en/without-otel': typeof DocsEnWithoutOtelRoute
  '/docs/en/without-otel-transfer': typeof DocsEnWithoutOtelTransferRoute
  '/docs/tr/with-otel': typeof DocsTrWithOtelRoute
  '/docs/tr/without-otel': typeof DocsTrWithoutOtelRoute
  '/docs/tr/without-otel-transfer': typeof DocsTrWithoutOtelTransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/task'
    | '/docs/en/with-otel'
    | '/docs/en/without-otel'
    | '/docs/en/without-otel-transfer'
    | '/docs/tr/with-otel'
    | '/docs/tr/without-otel'
    | '/docs/tr/without-otel-transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/task'
    | '/docs/en/with-otel'
    | '/docs/en/without-otel'
    | '/docs/en/without-otel-transfer'
    | '/docs/tr/with-otel'
    | '/docs/tr/without-otel'
    | '/docs/tr/without-otel-transfer'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/task'
    | '/docs/en/with-otel'
    | '/docs/en/without-otel'
    | '/docs/en/without-otel-transfer'
    | '/docs/tr/with-otel'
    | '/docs/tr/without-otel'
    | '/docs/tr/without-otel-transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  TaskRoute: typeof TaskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/task': {
      id: '/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof TaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/tr/without-otel-transfer': {
      id: '/docs/tr/without-otel-transfer'
      path: '/tr/without-otel-transfer'
      fullPath: '/docs/tr/without-otel-transfer'
      preLoaderRoute: typeof DocsTrWithoutOtelTransferRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/tr/without-otel': {
      id: '/docs/tr/without-otel'
      path: '/tr/without-otel'
      fullPath: '/docs/tr/without-otel'
      preLoaderRoute: typeof DocsTrWithoutOtelRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/tr/with-otel': {
      id: '/docs/tr/with-otel'
      path: '/tr/with-otel'
      fullPath: '/docs/tr/with-otel'
      preLoaderRoute: typeof DocsTrWithOtelRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/en/without-otel-transfer': {
      id: '/docs/en/without-otel-transfer'
      path: '/en/without-otel-transfer'
      fullPath: '/docs/en/without-otel-transfer'
      preLoaderRoute: typeof DocsEnWithoutOtelTransferRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/en/without-otel': {
      id: '/docs/en/without-otel'
      path: '/en/without-otel'
      fullPath: '/docs/en/without-otel'
      preLoaderRoute: typeof DocsEnWithoutOtelRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/en/with-otel': {
      id: '/docs/en/with-otel'
      path: '/en/with-otel'
      fullPath: '/docs/en/with-otel'
      preLoaderRoute: typeof DocsEnWithOtelRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsEnWithOtelRoute: typeof DocsEnWithOtelRoute
  DocsEnWithoutOtelRoute: typeof DocsEnWithoutOtelRoute
  DocsEnWithoutOtelTransferRoute: typeof DocsEnWithoutOtelTransferRoute
  DocsTrWithOtelRoute: typeof DocsTrWithOtelRoute
  DocsTrWithoutOtelRoute: typeof DocsTrWithoutOtelRoute
  DocsTrWithoutOtelTransferRoute: typeof DocsTrWithoutOtelTransferRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsEnWithOtelRoute: DocsEnWithOtelRoute,
  DocsEnWithoutOtelRoute: DocsEnWithoutOtelRoute,
  DocsEnWithoutOtelTransferRoute: DocsEnWithoutOtelTransferRoute,
  DocsTrWithOtelRoute: DocsTrWithOtelRoute,
  DocsTrWithoutOtelRoute: DocsTrWithoutOtelRoute,
  DocsTrWithoutOtelTransferRoute: DocsTrWithoutOtelTransferRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  TaskRoute: TaskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
